title:             rainsound's blog
email:             rainsound128@gmail.com
description:       개발 공부 중입니다.
author:            Sungwoo Kang
baseurl:           ""
url:               "https://rainsound-k.github.io"

# Social Profiles
twitter_username:
github_username:   rainsound-k
facebook_username:

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
