title:             rainsound 블로그
email:             rainsound128@gmail.com
description:       개발 공부하면서 까먹지 않기 위해 기록하는 블로그입니다.
author:            rainsound
baseurl:           ""
url:               "https://rainsound-k.github.io"

# Social Profiles
twitter_username:
github_username:   rainsound-k
facebook_username:

# Build settings
highlighter: rouge
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
